# Generated by Django 3.1.7 on 2021-03-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invorterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
