# Generated by Django 3.1.7 on 2021-03-02 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invorterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QA',
            new_name='Message',
        ),
    ]
